---
title: "PSD Classifier"
output: html_notebook
---


# Setup
```{r}
library(pacman)
p_load(dplyr, tidyverse, glmnet, randomForest, tree, ggplot2, skimr, ggRandomForests, xgboost, kableExtra, keras, neuralnet, tensorflow, ggpubr, effectsize, pROC, verification, MASS, pracma, ROCR)
```

Read in the data
```{r}
data <- read.csv('EEG_CSV/PSD_Classifier_Input.csv', header = FALSE)
data[,101] <- as.factor(data[,101]) # Turn the response variable into a factor
data[,102] <- as.factor(data[,102]) # subject id
colnames(data)[101] <- c("dose")
colnames(data)[102] <- c("subject.id")
head(data, 6)
```

# Random Forest Leave One Out
```{r}
prediction.error.psd <- rep(0,6)

for (i in 1:6){
  train.x <- data[(as.numeric(data$subject.id) != i),]
  test.x <- data[(as.numeric(data$subject.id) == i),]
  
  # train the model
  rf_classifier_x <- randomForest(data = train.x,        # Pass in the data
                              x = train.x[,1:100],   # Select the predictor variables 
                              y = train.x[,101],       # Select the response variable
                              ntree = 500,           # Select the range of number of trees to try
                              mtry = 6)             # Select the number of variables for each tree to use 
  
  pred.x <- predict(rf_classifier_x, test.x[,1:100]) # Get prediction for left-out subject
  prediction.error.psd[i] <- sum(pred.x != test.x[,101])/dim(test.x)[1] # calculate the error rate
  #prediction.error[i] <- mean(predicted.x$class==test.x$dose)
} 
prediction.error.psd


```

```{r}
# Plot Leave-One-Out Error By Subject
pe <- data.frame(prediction.error)
pe$Left_Out_Subject <- c("Subject 1", "Subject 2", "Subject 3", "Subject 4", "Subject 5", "Subject 6")
colnames(pe)[1] <- c("Prediction_Error")
jpeg(file="C:/Users/diego/Desktop/EEGStabilityGroupFigures/PSD_LeaveOneOut_PredictionError.jpeg", width = 300, height = 200, units='mm', res = 300)
ggplot(data = pe, aes(y=Prediction_Error, x=Left_Out_Subject))+
  geom_col(fill='aquamarine4') + 
  ylim(c(0, 1)) +
  ggtitle("PSD Classifier 'Leave-One-Out' Prediction Error") +
  xlab("Left-out Subject") +
  ylab("Prediction Error") + 
  geom_text(aes(label=sprintf("%0.3f", round(Prediction_Error, digits = 3))), position=position_dodge(width=0.9), vjust=-0.25) +
  theme(plot.title = element_text(face="bold", size=15), axis.title = element_text(face="bold", size=15), axis.text = element_text(face="bold", size=15))
dev.off

```

```{r}
rf_classifier_psd <- randomForest(data = data,        # Pass in the data
                              x = data[,1:100],   # Select the predictor variables (0.8-1.2 Crit. Index)
                              y = data[,101],       # Select the response variable
                              ntree = 500,           # Select the range of number of trees to try
                              mtry = 6)             # Select the number of variables for each tree to use
plot(rf_classifier_psd)
```


```{r}
jpeg(file="C:/Users/diego/Desktop/EEGStabilityGroupFigures/PSD_Classifier_FeatureImportance.jpeg", width = 300, height = 200, units='mm', res = 300)
rf_psd_feature_importance <- data.frame(importance(rf_classifier_psd), Frequency_Hz = seq(1, 100, by = 2))
ggplot(data = rf_psd_feature_importance, aes(x=Frequency_Hz, y=MeanDecreaseGini)) + 
  geom_bar(stat="identity", fill="darkcyan") +
  ggtitle("PSD Classifier Feature Importance") + 
  theme(plot.title = element_text(face="bold", size=15), axis.title = element_text(face="bold", size=15), axis.text = element_text(face="bold", size=15)) 
dev.off()
```
